# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  bookifyapi:
    image: bookifyapi
    build:
      context: .
      dockerfile: source/Bookify/src/Bookify.Api/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 1337:1337
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
