### Secured route without token = failwhale

GET http://localhost:5000/api/v1/apartments?startDate=2025-09-28&endDate=2025-09-30
Accept: application/json

### Register a new user in the system and with keycloak

POST http://localhost:5000/api/v1/users/register
Content-Type: application/json

{
  "email": "bill@microsoft.com",
  "firstName": "Bill",
  "lastName": "Gates",
  "password": "12345"
}

### Retrieve and save token

POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
  "email": "bill@microsoft.com",
  "password": "12345"
}

> {% client.global.set("auth_token", response.body.accessToken); %}

### Secured route with token = win

GET http://localhost:5000/api/v1/apartments?startDate=2025-09-28&endDate=2025-09-30
Accept: application/json
Authorization: Bearer {{auth_token}}

###

GET http://localhost:5000/api/v1/users/me

###
